Drakkar-Software/OctoBot-Backtesting

octobot_backtesting/api/data_file.py, octobot_backtesting/api/exchange_data_collector.py, octobot_backtesting/collectors/data_collector.pxd, octobot_backtesting/collectors/data_collector.py, octobot_backtesting/collectors/exchanges/abstract_exchange_history_collector.pxd, octobot_backtesting/collectors/exchanges/abstract_exchange_history_collector.py, octobot_backtesting/collectors/exchanges/abstract_exchange_live_collector.pxd, octobot_backtesting/collectors/exchanges/abstract_exchange_live_collector.py, octobot_backtesting/collectors/exchanges/exchange_collector.pxd, octobot_backtesting/collectors/exchanges/exchange_collector.py, octobot_backtesting/data/data_file_manager.py, octobot_backtesting/enums.py, octobot_backtesting/importers/exchanges/exchange_importer.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/69
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/71
=> data_collector_update_for_web_interface_call 

octobot_backtesting/api/backtesting.py, octobot_backtesting/api/data_file.py, octobot_backtesting/backtesting.py, octobot_backtesting/data/data_file_manager.py, octobot_backtesting/importers/data_importer.py, octobot_backtesting/independent_backtesting.pxd, octobot_backtesting/independent_backtesting.py, octobot_backtesting/octobot_backtesting.pxd, octobot_backtesting/octobot_backtesting.py, octobot_backtesting/producers/time_updater.py, setup.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/88
requirs https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/28
=> Add independent backtesting to run backtesting within an existing bot 

octobot_backtesting/octobot_backtesting.py
possible after https://github.com/Drakkar-Software/OctoBot-Trading/pull/108
=> handle missing exchange manager on stop

tests/api/__init__.py, tests/api/test_backtesting.py, tests/api/test_data_file.py, tests/api/test_data_file_converters.py, tests/api/test_exchange_data_collector.py, tests/api/test_importer.py
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/35
=> add minimal tests

octobot_backtesting/backtesting.py, octobot_backtesting/channels/time.py, octobot_backtesting/independent_backtesting.py, octobot_backtesting/octobot_backtesting.py, octobot_backtesting/producers/time_updater.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19
=> update exception logger

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt
**Requirements**
- Commons version to 1.3.0
- CCXT version to 1.23.67
=> [Version] v1.3.11

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt, setup.py
**Requirements**
- Commons version to 1.3.5
- Cython version to 0.29.16
- Channels version to 1.3.22
=> [Version] v1.3.12 

octobot_backtesting/abstract_backtesting_test.pxd, octobot_backtesting/abstract_backtesting_test.py, octobot_backtesting/api/backtesting.py, octobot_backtesting/api/strategy_optimizer.py, octobot_backtesting/independent_backtesting.pxd, octobot_backtesting/independent_backtesting.py, octobot_backtesting/octobot_backtesting.pxd, octobot_backtesting/octobot_backtesting.py, octobot_backtesting/strategy_optimizer/strategy_optimizer.pxd, octobot_backtesting/strategy_optimizer/strategy_optimizer.py, octobot_backtesting/strategy_optimizer/strategy_test_suite.py, requirements.txt, tests/api/test_backtesting.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/28
=> tentacle_manager integration 

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/backtesting.py, octobot_backtesting/util/backtesting_util.py, requirements.txt
=> Fix wildcard imports

octobot_backtesting/abstract_backtesting_test.py, octobot_backtesting/octobot_backtesting.pxd, octobot_backtesting/octobot_backtesting.py
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/14
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/42
=> tentacles migration adaptations 

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt
=> [Version] v1.3.15  

octobot_backtesting/api/backtesting.py, octobot_backtesting/independent_backtesting.py, octobot_backtesting/octobot_backtesting.py, octobot_backtesting/strategy_optimizer/strategy_optimizer.pxd, octobot_backtesting/strategy_optimizer/strategy_optimizer.py, octobot_backtesting/strategy_optimizer/strategy_test_suite.py
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/54
=> Update matrix creation and evaluators activation 

octobot_backtesting/independent_backtesting.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/46
=> handle backtesting errors

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/abstract_backtesting_test.py, octobot_backtesting/api/backtesting.py, octobot_backtesting/collectors/social/social_collector.py, octobot_backtesting/data/database.py, octobot_backtesting/importers/exchanges/exchange_importer.py, octobot_backtesting/octobot_backtesting.pxd, octobot_backtesting/octobot_backtesting.py, octobot_backtesting/producers/time_updater.py, octobot_backtesting/strategy_optimizer/strategy_optimizer.py, requirements.txt, setup.py
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/48
=> improve debug logs and time management

octobot_backtesting/octobot_backtesting.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/177
=> set exchange builder bot it

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt
=> [Version] v1.5.2

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt
=> [Version] v1.5.3

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/api/data_file.py, octobot_backtesting/data/data_file_manager.pxd
=> [Version] v1.5.7

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/channels_manager/channels_manager.py, requirements.txt
- [ChannelsManager] Iterates on ChannelConsumerPriorityLevels
=> [Version] v1.5.8

CHANGELOG.md, Makefile, README.md, octobot_backtesting/__init__.py, requirements.txt
=> [Version] v1.5.10

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/collectors/exchanges/exchange_collector.pxd
- [ExchangeCollector] Cython header
=> [Version] v1.5.11

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/api/data_file_converters.py, octobot_backtesting/api/exchange_data_collector.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88
=> Remove advanced manager

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt, setup.py
=> [Version] v1.5.14

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt, setup.py
=> [Version] v1.5.17

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt, setup.py
- Requirements
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/103
=> [Version] v1.5.19

octobot_backtesting/api/__init__.py, octobot_backtesting/api/backtesting.py, octobot_backtesting/api/importer.py, octobot_backtesting/backtesting.py, octobot_backtesting/util/__init__.py, octobot_backtesting/util/backtesting_util.py
fixes https://github.com/Drakkar-Software/OctoBot/issues/1514
=> Use default importer

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, requirements.txt, setup.py
=> [Version] v1.6.13

octobot_backtesting/api/data_file.py, octobot_backtesting/data/data_file_manager.py, octobot_backtesting/enums.py
Add timestamp to data_file description. Need to sort data file by date
=> Add timestamp to data_file description

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/api/importer.py, octobot_backtesting/collectors/exchanges/exchange_collector.py, octobot_backtesting/importers/exchanges/exchange_importer.pxd, octobot_backtesting/importers/exchanges/exchange_importer.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/246
=> [Symbols] update for symbol object in backtesting file

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/api/__init__.py, octobot_backtesting/api/backtesting.py, octobot_backtesting/api/importer.py, octobot_backtesting/backtest_data.pxd, octobot_backtesting/backtest_data.py, octobot_backtesting/backtesting.py, octobot_backtesting/channels_manager.pxd, octobot_backtesting/channels_manager.py, octobot_backtesting/importers/data_importer.py, octobot_backtesting/time/channel/time_updater.py, requirements.txt, setup.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/303
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/148
=> backtester req

CHANGELOG.md, README.md, octobot_backtesting/__init__.py, octobot_backtesting/collectors/exchanges/exchange_collector.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/356
=> add delete_all to exchange collector
